name: Run Tests
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
        - os: macos-latest
        - os: windows-latest
          toolchain-suffix: -gnu
        - os: windows-latest
          toolchain-suffix: -msvc
        - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable${{ matrix.toolchain-suffix }}
    - name: Build library
      run: |
        cargo build
    - name: Run tests
      run: |
        cargo test
    - name: Check packaging
      run: |
        cargo package

  check-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: rustfmt
      run: |
        cargo fmt -- --check
    - name: clippy
      run: |
        cargo clippy --all-targets -- -D warnings
    - name: docs
      run: |
        cargo doc
